"use client";

import { useState, useTransition } from "react";
import { saveHistoricalInspection } from "@/actions/mutations";

const CONDITIONS = ["", "good", "fair", "needs_repair", "damaged", "significantly_damaged", "removed", "inaccessible"];

export function HistoricalInspection({ buildings, initialBuilding, materials, newerCount }: { buildings: { id: string; name: string; buildingNumber: string }[]; initialBuilding?: string; materials: { id: string; inventoryCode: string; materialDescription: string; floor: string | null; room: string | null; condition: string }[]; newerCount: number }) {
  const [buildingId, setBuildingId] = useState(initialBuilding || ""); const [date, setDate] = useState(""); const [inspectorName, setInspectorName] = useState(""); const [values, setValues] = useState<Record<string, string>>({}); const [pending, start] = useTransition();
  const completedAfter = date && newerCount > 0;
  return <div className="space-y-4"><div className="rounded-xl border border-[rgba(16,36,72,0.1)] bg-teal-soft p-4 text-sm"><b>Historical record.</b> {date ? completedAfter ? `${newerCount} completed inspection(s) exist after this date, so current conditions and surveillance dates will not change.` : "This is the most recent inspection on record — saving will update current conditions and building dates." : "Choose the performed date to see how this entry affects current records."}</div><div className="grid gap-3 md:grid-cols-3"><label className="field"><span>Building</span><select value={buildingId} onChange={(e) => { setBuildingId(e.target.value); window.location.assign(`/inspections/new/historical?building=${e.target.value}`); }}><option value="">Choose building</option>{buildings.map((b) => <option key={b.id} value={b.id}>{b.buildingNumber} · {b.name}</option>)}</select></label><label className="field"><span>Date performed</span><input required type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><label className="field"><span>Inspector as recorded</span><input value={inspectorName} onChange={(e) => setInspectorName(e.target.value)} /></label></div>{buildingId && <><div className="sticky top-0 z-10 flex flex-wrap gap-2 bg-paper py-2"><button className="btn btn-ghost text-xs" onClick={() => setValues(Object.fromEntries(materials.map((m) => [m.id, "good"])))}>Set all to Good</button><span className="ml-auto text-xs text-ink-3">{Object.values(values).filter(Boolean).length} of {materials.length} filled</span></div><div className="table-wrap"><table className="data"><thead><tr><th>ID</th><th>Material</th><th>Location</th><th>On record then</th><th>Condition</th></tr></thead><tbody>{materials.map((m) => <tr key={m.id}><td className="mono-id">{m.inventoryCode}</td><td>{m.materialDescription}</td><td>{[m.floor, m.room].filter(Boolean).join(" · ")}</td><td>{m.condition}</td><td><select value={values[m.id] || ""} onChange={(e) => setValues((old) => ({ ...old, [m.id]: e.target.value }))}>{CONDITIONS.map((condition) => <option key={condition} value={condition}>{condition ? condition.replaceAll("_", " ") : "Not inspected"}</option>)}</select></td></tr>)}</tbody></table></div><p className="text-xs text-ink-3">Blank rows are valid and will not write an inspection item.</p><button disabled={pending || !date || !inspectorName} className="btn btn-primary" onClick={() => start(async () => { const result = await saveHistoricalInspection({ buildingId, inspectionType: "annual_inspection", performedAt: new Date(`${date}T12:00:00`), inspectorName, status: "completed", items: materials.map((m) => ({ inventoryItemId: m.id, currentCondition: values[m.id] || undefined })) }); window.location.assign(`/inspections/${result.id}`); })}>Save historical inspection</button></>}</div>;
}
